CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name_role character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.tvs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description_tv character varying(200) COLLATE pg_catalog."default",
    name_tv character varying(50) COLLATE pg_catalog."default",
    price_tv integer NOT NULL,
    ordersfk_id bigint,
    CONSTRAINT tvs_pkey PRIMARY KEY (id),
    CONSTRAINT fktnqp32wshl14jpv13mm7p52o9 FOREIGN KEY (ordersfk_id)
        REFERENCES public.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.transports
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name_transport character varying(50) COLLATE pg_catalog."default",
    number_transport character varying(6) COLLATE pg_catalog."default",
    CONSTRAINT transports_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.staffs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fio character varying(100) COLLATE pg_catalog."default",
    work_experience integer NOT NULL,
    departmentsfk_id bigint,
    rolesfk_id bigint,
    login character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    date date,
    CONSTRAINT staffs_pkey PRIMARY KEY (id),
    CONSTRAINT fke1lpe8s6tfnbd7ti28tveto64 FOREIGN KEY (rolesfk_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkp48w4pstqk4nhrw737wkdyx4h FOREIGN KEY (departmentsfk_id)
        REFERENCES public.departments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT staffs_work_experience_check CHECK (work_experience <= 40)
)
CREATE TABLE IF NOT EXISTS public.departments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name_departments character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT departments_pkey PRIMARY KEY (id)
)
CREATE TABLE IF NOT EXISTS public.suppliers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    staffsfk bigint,
    transportsfk bigint,
    CONSTRAINT suppliers_pkey PRIMARY KEY (id),
    CONSTRAINT ukcu4oary4sb41doeygvn01ysei UNIQUE (transportsfk),
    CONSTRAINT uksucd0hl9novuhg740pp8x5nm9 UNIQUE (staffsfk),
    CONSTRAINT fk2xfnal39jx33qf4lc8bp61g3h FOREIGN KEY (transportsfk)
        REFERENCES public.transports (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkcg6qrx2ewb4805966k14b0pri FOREIGN KEY (staffsfk)
        REFERENCES public.staffs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.couriers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    staffsfk bigint,
    transportsfk bigint,
    CONSTRAINT couriers_pkey PRIMARY KEY (id),
    CONSTRAINT ukd55ymbmygsvofnfo5o4drqnse UNIQUE (staffsfk),
    CONSTRAINT ukd64kswnfth5xg2vpgbmeyh67q UNIQUE (transportsfk),
    CONSTRAINT fkgsxnt5twudslpr8qepuosq08u FOREIGN KEY (staffsfk)
        REFERENCES public.staffs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkpwp7ld1lfraq2ri8pm5syamjv FOREIGN KEY (transportsfk)
        REFERENCES public.transports (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    number_orders integer NOT NULL,
    prise integer NOT NULL,
    couriersfk bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT uk46jqgniwjvbtguhpl48o49j1f UNIQUE (couriersfk),
    CONSTRAINT fk48ksylurjjrg69vkvrsngt6xj FOREIGN KEY (couriersfk)
        REFERENCES public.couriers (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)